kind: pipeline
name: production
steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --recursive --remote
      
  - name: docker  
    image: plugins/docker
    settings:
      repo: metadonors/odoo
      mirror: http://registry:5000
      tags: 
        - 12.0
      username:
        from_secret: docker_login
      password:
        from_secret: docker_password
  
      
trigger:
  branch:
    - 12.0
  event:
    - push

