version: '3'
volumes:
    data_odoo:
    pgdata_odoo:
services:
  odoo:
    build: odoo
    ports:
      - 8069:8069
      - 8072:8072
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    environment:
      - ODOO_DB_HOST=postgres
      - ODOO_DB_NAME=demo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
    volumes:
      - "data_odoo:/var/lib/odoo/"
      # mount volumes for dev needs
      - "./addons:/mnt/dev-addons"
    # launch container in odoo dev mode
    command: run --dev=all
  nginx:
    build: web
    ports:
       - 80:80
    links:
      - "odoo:odoo"
  postgres:
    image: postgres:10.0
    ports:
       - 5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "pgdata_odoo:/var/lib/postgresql/data"

  