version: '3'
volumes:
    data_odoo_12:
    pgdata_odoo_12:
services:
  odoo:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    environment:
      - ODOO_DB_HOST=postgres
      - ODOO_DB_NAME=odoo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_WORKERS=4
      - ODOO_LIMIT_MEMORY_HARD=6845104128
      - ODOO_LIMIT_MEMORY_SOFT=5704253440
    volumes:
      - "data_odoo_12:/var/lib/odoo/"
    command: run --dev=all
  postgres:
    image: postgres:10.0
    ports:
       - 5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "pgdata_odoo_12:/var/lib/postgresql/data"

  
