version: '3'
volumes:
    data_odoo:
    pgdata_odoo:
services:
  odoo:
    build: odoo
    image: metadonors/odoo:11.0
    container_name: odoo
    ports:
      - 8069:8069
      - 8072:8072
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    environment:
      - ODOO_DB_HOST=postgres
      - ODOO_DB_NAME=demo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
    volumes:
      - "data_odoo:/var/lib/odoo/"
      # mount volumes for dev needs
      #- "./odoo/project_addons:/srv/webapp/project_addons"
      #- "./odoo/amnesty_addons:/srv/webapp/amnesty_addons"
      #- "./tmp:/srv/webapp/tmp"
    # launch container in odoo dev mode
    # command: run --dev
  nginx:
    build: web
    image: metadonors/nginx_odoo:latest
    container_name: odoo_nginx
    ports:
       - 80:80
  postgres:
    image: postgres:10.0
    container_name: odoo_postgres
    ports:
       - 5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "pgdata_odoo:/var/lib/postgresql/data"

  